config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments, only: [ :create, :destroy ], module: :project
  end

  ## Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "profile", to: "home#index", as: :profile

  root "projects#index"
end

app/views/shared/_footer.html.slim
footer.bg-gray-50.text-base
  .container-fluid.py-4.px-6
    span= link_to '👤 Profile', profile_path

app/views/shared/_timeline_item.html.slim
- user = local_assigns.fetch(:user)
.p-6.border-b.border-gray-200.bg-gray-50
  .flex.items-start.space-x-4
    .flex-shrink-0
      - if user.github_username.present?
        = image_tag github_avatar_url(user.github_username, size: 40), class: "h-10 w-10 rounded-full", alt: user.full_name
      - else
        .h-10.w-10.rounded-full.bg-gray-200.flex.items-center.justify-center
          span.text-gray-500.text-sm= user.initials
    .flex-1
      .flex.items-center.space-x-2
        .text-sm.font-medium.text-gray-900= user.full_name
        .text-xs.text-gray-500 • #{time_ago_in_words(local_assigns.fetch(:created_at))} ago
      = yield :action if content_for?(:action)
      .mt-2.text-sm.text-gray-700
        = yield