config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments, only: [ :create, :destroy ], module: :project
  end

  ## Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "profile", to: "home#index", as: :profile

  root "projects#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.slim
p
  | Signed in as 
  = Current.user.email
h2 Login and verification
div= link_to "Change password", edit_password_path
div= link_to "Change email address", edit_identity_email_path
h2 Access history
div= link_to "Devices & Sessions", sessions_path
br
= button_to "Log out", Current.session, method: :delete