config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments, only: [ :create, :destroy ], module: :project
  end

  ## Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "profile", to: "home#index", as: :profile

  root "projects#index"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  enum :status, { pending: 0, active: 1, complete: 2, archived: 3 }

  # Associations
  has_many :comments, class_name: "Project::Comment", dependent: :destroy
  has_many :status_changes, class_name: "Project::StatusChange", dependent: :destroy
  has_many :events, -> { order(created_at: :asc) }, class_name: "Project::Event", dependent: :destroy
  has_many :users, through: :events, source: :eventable, source_type: "User"

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :status, presence: true

  # Callbacks
  before_validation :set_default_status, on: :create
  after_save :create_status_change!, if: :saved_change_to_status?

  private

  def set_default_status
    self.status ||= :pending
  end

  def create_status_change!
    return unless user = Current.user # Skip if no user context (i.e. tests or console)
    from_status = saved_change_to_status[0] || "pending"
    to_status   = saved_change_to_status[1]

    status_changes.create!(user:, from_status:, to_status:)
  end
end

app/models/project/comment.rb
# == Schema Information
#
# Table name: project_comments
#
#  id         :integer          not null, primary key
#  body       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_project_comments_on_project_id  (project_id)
#  index_project_comments_on_user_id     (user_id)
#
# Foreign Keys
#
#  project_id  (project_id => projects.id)
#  user_id     (user_id => users.id)
#
class Project::Comment < ApplicationRecord
  # Concerns
  include Project::Concerns::Eventable

  # Associations
  belongs_to :project
  belongs_to :user

  # Validations
  validates :body, presence: true
end

app/models/project/concerns/eventable.rb
module Project::Concerns::Eventable
  extend ActiveSupport::Concern

  included do
    # Associations
    belongs_to :project
    belongs_to :user

    has_one :event, as: :eventable, dependent: :destroy

    # Callbacks
    after_create :create_event!
    after_create_commit :update_turbo_stream
  end

  def to_partial_path # slight modification of convention for better template organization
    name = self.class.name.demodulize.underscore
    "projects/#{name.pluralize}/#{name}"
  end

  private

  def create_event!
    project.events.create!(eventable: self)
  end

  def update_turbo_stream
      broadcast_append_to project,
        target: "timeline",
        partial: "projects/event",
        locals: { event: event }
  end
end

app/models/project/event.rb
# == Schema Information
#
# Table name: project_events
#
#  id             :integer          not null, primary key
#  eventable_type :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  eventable_id   :integer          not null
#  project_id     :integer          not null
#
# Indexes
#
#  index_project_events_on_eventable                  (eventable_type,eventable_id)
#  index_project_events_on_project_id                 (project_id)
#  index_project_events_on_project_id_and_created_at  (project_id,created_at)
#
# Foreign Keys
#
#  project_id  (project_id => projects.id)
#
class Project::Event < ApplicationRecord
  # Associations
  belongs_to :eventable, polymorphic: true

  # Delegations
  delegate :project, :user, to: :eventable

  def to_partial_path # slight modification of convention for cleaner template organization
    "projects/event"
  end

  def associated_user
    eventable.is_a?(User) ? eventable : eventable.user
  end
end

app/models/project/status_change.rb
# == Schema Information
#
# Table name: project_status_changes
#
#  id          :integer          not null, primary key
#  from_status :string           not null
#  to_status   :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :integer          not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_project_status_changes_on_project_id  (project_id)
#  index_project_status_changes_on_user_id     (user_id)
#
# Foreign Keys
#
#  project_id  (project_id => projects.id)
#  user_id     (user_id => users.id)
#
class Project::StatusChange < ApplicationRecord
  # Concerns
  include Project::Concerns::Eventable

  # Associations
  belongs_to :project
  belongs_to :user

  # Validations
  validates :from_status, :to_status, presence: true
end

app/controllers/project/comments_controller.rb
class Project::CommentsController < ApplicationController
  before_action :set_project

  def create
    @comment = @project.comments.build(comment_params)
    @comment.user = Current.user

    if @comment.save
      redirect_to @project, notice: "Comment was successfully added."
    else
      redirect_to @project, alert: "Error adding comment."
    end
  end

  def destroy
    @comment = @project.comments.find(params[:id])
    @comment.destroy
    redirect_to @project, notice: "Comment was successfully removed."
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:project_comment).permit(:body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.includes(
      events: [
        :eventable,
        { eventable: :user }  # Preload users through eventable polymorphic association
      ],
      comments: :user,
      status_changes: :user
    ).find(params[:id])
  end

  def project_params
    params.fetch(:project, {}).permit(:name, :status)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_status_color_class
    {
      "pending" => "bg-yellow-100 text-yellow-800",
      "active" => "bg-green-100 text-green-800",
      "complete" => "bg-blue-100 text-blue-800",
      "archived" => "bg-gray-100 text-gray-800"
    }
  end
end

app/views/projects/_event.html.slim
div id=dom_id(event.eventable) class="p-6 border-b border-gray-200 bg-gray-50"
  - user = event.associated_user
  .flex.items-start.space-x-4
    .flex-shrink-0
      - if user&.github_username.present?
        = image_tag github_avatar_url(user.github_username, size: 40), class: "h-10 w-10 rounded-full", alt: user.full_name
      - else
        .h-10.w-10.rounded-full.bg-gray-200.flex.items-center.justify-center
          span.text-gray-500.text-sm= user&.initials
    .flex-1
      .flex.items-center.space-x-2
        .text-sm.font-medium.text-gray-900= user&.full_name
        .text-xs.text-gray-500 • #{time_ago_in_words(event.created_at)} ago
    = render event.eventable

app/views/projects/_form.html.slim
= form_with(model: @project, local: true) do |f|
  = errors_for(@project)
  
  = f.label :name, class: 'block text-gray-700 text-sm font-bold mb-2'
  = f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-4'

  = f.label :status, class: 'block text-gray-700 text-sm font-bold mb-2'
  = f.select :status, Project.statuses.keys.map { |s| [s.titleize, s] }, {}, class: 'shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-4'

  = f.submit class: 'my-2 bg-blue-500 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded w-full'

app/views/projects/_project.html.slim
div id=dom_id(project) class="bg-white overflow-hidden shadow rounded-lg hover:shadow-lg transition-shadow duration-200"
  .px-4.py-5.sm:p-6
    .flex.items-center.justify-between
      .flex.items-center
        .flex-shrink-0
          div class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium #{project_status_color_class[project.status]}"
            = project.status.titleize
      .flex-shrink-0
        .flex.items-center.space-x-2
          = link_to project_path(project), class: "text-indigo-600 hover:text-indigo-900" do
            span.sr-only View project
            svg.h-5.w-5 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
              path d="M10 12a2 2 0 100-4 2 2 0 000 4z"
              path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"
          = link_to edit_project_path(project), class: "text-gray-400 hover:text-gray-500" do
            span.sr-only Edit project
            svg.h-5.w-5 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
              path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"
          = button_to project_path(project), 
              class: "text-gray-400 hover:text-red-500",
              form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }} do
            span.sr-only Delete project
            svg.h-5.w-5 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
              path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"
    .mt-4
      = link_to project_path(project) do
        h3.text-lg.font-medium.text-gray-900= project.name

app/views/projects/edit.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3
      Projects
    = render 'form', project: @project

= link_to 'Show', @project
'&nbsp;|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
.max-w-7xl.mx-auto.px-4.sm:px-6.lg:px-8.py-8
  .flex.items-center.justify-between.mb-8
    h1.text-3xl.font-bold.text-gray-900 Projects
    = link_to new_project_path, class: 'inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' do
      svg.-ml-1.mr-2.h-5.w-5 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
        path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd"
      | New Project

  .grid.grid-cols-1.gap-4.sm:grid-cols-2.lg:grid-cols-3
    = render @projects

app/views/projects/new.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3
      | New Projects

    = render 'form', project: @project
    = link_to 'Back', projects_path

app/views/projects/show.html.slim
.max-w-4xl.mx-auto.px-4.py-8
  .flex.items-center.justify-between.mb-6
    h1.text-3xl.font-bold.text-gray-900= @project.name
    .flex.items-center.space-x-4
      = link_to 'Edit', edit_project_path(@project), class: 'text-indigo-600 hover:text-indigo-900'
      = link_to 'Back', projects_path, class: 'text-gray-600 hover:text-gray-900'
  
  .bg-white.shadow.rounded-lg.overflow-hidden
    .px-6.py-4.border-b.border-gray-200
      .flex.items-center.space-x-2
        span.text-sm.font-medium.text-gray-500 Status:
        span.inline-flex.items-center.px-2.py-1.rounded-full.text-xs.font-medium class=project_status_color_class[@project.status]
          = @project.status.titleize

    .divide-y.divide-gray-200#timeline
      = render partial: 'projects/event', collection: @project.events
      = turbo_stream_from @project

    = render "projects/comments/form"